### ISSUE TITLE
Un nuevo comienzo

### ISSUE THREAD

**Issue by edgar210** [edgar210/PDPLUNES7AMEQUIPO-1#1]
Los inicios de algo nuevo pueden ser difíciles
Pero solo es miedo a lo desconocido
Es nuestra naturaleza sentir miedo
![hombre-preocupado-619x346 1](https://user-images.githubusercontent.com/42661499/44951664-8dc51700-ae2f-11e8-87d3-84501551f7e4.jpg)

Normalmente el miedo es incierto
Se tienen razones pero a veces no
El miedo es algo incierto 
Pero ciertamente, es algo desconocido
Ya que se pueden tener varias razones 
Pero siempre lo principal es lo desconocido.

**Comment by CESARSOAD07** [comment]
acabo de agregar los cambios a la issue presentada
